pipeline {
    agent any
    stages {
        stage('Checkout GIT') {
              steps {
                  checkout([
                       $class: 'GitSCM',
                        branches: [[name: 'main']],
                        userRemoteConfigs: [[url: 'https://github.com/mohamedamineboughrara/erp_project', credentialsId: '04d2b06c-1242-4e29-bec6-34e40f5735ec']]
                         ])
                       }
                   }

        stage('MVN CLEAN') {
            steps {
                sh 'mvn clean'
            }
        }

        stage('MVN COMPILE') {
            steps {
                sh 'mvn compile'
            }
        }

        stage('MVN PACKAGE') {
            steps {
                sh 'mvn package'
            }
        }

        stage('MVN TEST') {
            steps {
                sh 'mvn test'
            }
        }



        	 stage('Build docker image'){
                      steps{
                              script{
                                  sh 'docker build -t mohamedamineboughrara/micrpserviceprojet .'
                                                  }
                                                }
                                            }
                stage('Docker login') {

                                steps {
                                  sh 'echo "login Docker ...."'
                                  sh 'docker login -u mohamedamineboughrara -p azerty123'
                                             }  }
                stage('Docker push') {

                                steps {
                                    sh 'echo "Docker is pushing to ...."'
                                	sh 'docker push mohamedamineboughrara/micrpserviceprojet'
                                             }  }



      }
    }
